import { createFileRoute, Link } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { CheckCircle2, Loader2, RefreshCcw, Smartphone, XCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { getOrderStatus,startMpesaPayment } from "@/lib/checkout.functions";
import { useCart } from "@/lib/cart";
import { money } from "@/lib/storefront";
const schema=z.object({waiting:z.coerce.boolean().catch(false)});
export const Route=createFileRoute("/order/$orderId")({validateSearch:(search)=>schema.parse(search),head:()=>({meta:[{title:"Order status — Scentlyn"},{name:"description",content:"Check the status of your Scentlyn order."},{property:"og:title",content:"Order status — Scentlyn"},{property:"og:description",content:"Check the status of your Scentlyn order."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"},{name:"robots",content:"noindex"}]}),component:OrderPage});
type Order=Awaited<ReturnType<typeof getOrderStatus>>;
function OrderPage(){const {orderId}=Route.useParams();const {waiting}=Route.useSearch();const getStatusFn=useServerFn(getOrderStatus);const startMpesaFn=useServerFn(startMpesaPayment);const [order,setOrder]=useState<Order>(null);const [loading,setLoading]=useState(true);const [retrying,setRetrying]=useState(false);const [timedOut,setTimedOut]=useState(false);const [error,setError]=useState("");const cart=useCart();const load=async()=>{try{const result=await getStatusFn({data:{orderId}});setOrder(result);if(result&&(result.payment_status==="paid"||result.payment_method==="cod"))cart.clear()}catch{setError("We couldn't check this order right now.")}finally{setLoading(false)}};useEffect(()=>{load();const timer=window.setInterval(load,3500);const timeout=window.setTimeout(()=>setTimedOut(true),120_000);return()=>{window.clearInterval(timer);window.clearTimeout(timeout)}},[orderId,waiting]);const retry=async()=>{setRetrying(true);setTimedOut(false);setError("");try{const result=await startMpesaFn({data:{orderId}});if(!result.ok)setError(result.error)}catch{setError("M-Pesa could not be reached. Please try again.")}finally{setRetrying(false)}};if(loading)return <div className="mx-auto max-w-xl px-5 py-24 text-center"><Loader2 className="mx-auto size-10 animate-spin text-accent"/><p className="mt-4">Checking your order…</p></div>;if(!order)return <OrderShell icon={<XCircle/>} title="Order not found" body="We couldn't find this order."/>;const paid=order.payment_status==="paid";const cod=order.payment_method==="cod";const failed=order.payment_status==="failed"||order.status==="cancelled";if(paid||cod)return <OrderShell icon={<CheckCircle2/>} title={paid?"Payment received":"Order confirmed"} body={paid?"Thank you. We’re preparing your order.":"Thank you. You’ll pay when your order arrives."} order={order}/>;if(failed||timedOut)return <OrderShell icon={<XCircle/>} title={timedOut?"Payment is taking longer than expected":"Payment wasn’t completed"} body="Your order details are still saved. You can retry without filling the form again." order={order} action={<Button onClick={retry} disabled={retrying}>{retrying?<Loader2 className="animate-spin"/>:<RefreshCcw/>}Try M-Pesa again</Button>} error={error}/>;return <OrderShell icon={<Smartphone/>} title="Check your phone" body="Enter your M-Pesa PIN to complete payment. This page updates automatically when payment is confirmed." order={order} action={<Button variant="outline" onClick={retry} disabled={retrying}>{retrying?<Loader2 className="animate-spin"/>:<RefreshCcw/>}Send prompt again</Button>} error={error} pulse/>}
function OrderShell({icon,title,body,order,action,error,pulse}:{icon:React.ReactNode;title:string;body:string;order?:NonNullable<Order>;action?:React.ReactNode;error?:string;pulse?:boolean}){return <div className="mx-auto max-w-xl px-5 py-20 text-center"><div className={`mx-auto grid size-20 place-items-center rounded-full bg-secondary text-accent [&>svg]:size-10 ${pulse?"animate-pulse":""}`}>{icon}</div><h1 className="mt-6 font-display text-5xl font-semibold">{title}</h1><p className="mx-auto mt-3 max-w-md text-muted-foreground">{body}</p>{order&&<div className="mt-8 bg-card p-6 text-left"><div className="flex justify-between gap-4"><span>Order number</span><strong>{order.order_number}</strong></div><div className="mt-3 flex justify-between gap-4"><span>Total</span><strong>{money(Number(order.total))}</strong></div><div className="mt-3 flex justify-between gap-4"><span>Status</span><strong className="capitalize">{order.payment_status}</strong></div></div>}{error&&<p role="alert" className="mt-5 text-sm text-destructive">{error}</p>}<div className="mt-7 flex flex-wrap justify-center gap-3">{action}<Button variant="link" asChild><Link to="/">Continue shopping</Link></Button></div></div>}
